default:
	gcc -o prog main.c date.c input.c stringutils.c utils.c mapArrayList.c mapElem.c listArrayList.c listElem.c countries.c vaccinations.c stringCode.c
debug:
	gcc -g -o prog main.c date.c input.c stringutils.c utils.c mapArrayList.c mapElem.c listArrayList.c listElem.c countries.c vaccinations.c stringCode.c
clean:
	rm -f prog